In [1]:
import pandas as pd

In [10]:
cols = ['id','val_high','p_high','val_low','val_safe','sure','d1','mode']
est  = pd.read_csv('60competitionset.dat',   sep=r'\s+', header=None, names=cols)

In [11]:
est_final = est[['id','val_high','p_high','val_low','val_safe']].copy()
est_final.head()

   id  val_high  p_high  val_low  val_safe
0   1      -8.7    0.06    -22.8     -21.4
1   2      -2.2    0.09     -9.6      -8.7
2   3      -2.0    0.10    -11.2      -9.5
3   4      -1.4    0.02     -9.1      -9.0
4   5      -0.9    0.07     -4.8      -4.7

In [12]:
updated_records_est=[]
for _,row in est_final.iterrows():
    updated_records_est.append({
        'id': row['id'],
        'val_high': row['val_high'],
        'p_high': row['p_high'],
        'val_low': row['val_low'],
        'p_low': 1-row['p_high'],
        'val_safe': row['val_safe'],
        'p_safe': 1
    })

updated_est_df = pd.DataFrame(updated_records_est)
updated_est_df.head()

    id  val_high  p_high  val_low  p_low  val_safe  p_safe
0  1.0      -8.7    0.06    -22.8   0.94     -21.4       1
1  2.0      -2.2    0.09     -9.6   0.91      -8.7       1
2  3.0      -2.0    0.10    -11.2   0.90      -9.5       1
3  4.0      -1.4    0.02     -9.1   0.98      -9.0       1
4  5.0      -0.9    0.07     -4.8   0.93      -4.7       1

In [13]:
updated_est_df.to_csv('TPTcompetitionSet.csv', index=False)